tabWidth: 2
semi: false
overrides:
  - files:
      - '*.tsx'
      - '*.ts'
    options:
      parser: 'typescript'
      arrowParens: 'avoid'
      bracketSpacing: true
      proseWrap: 'never'
      singleQuote: true
      trailingComma: 'none'
      printWidth: 80
  - files:
      - '*.css'
    options:
      parser: 'css'
  - files:
      - '*.json'
    options:
      parser: 'json'
  - files:
      - '*.yaml'
      - '*.yml'
    options:
      parser: 'yaml'
      singleQuote: true
  - files:
      - '*.md'
    options:
      parser: 'mdx'
