name: 'Mobile CI'

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Mobile Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      - name: Install dependencies
        run: |
          yarn install
          npx lerna bootstrap

      - name: Install dependencies
        working-directory: ./packages/mobile
        run: yarn install

      - name: Build
        working-directory: ./packages/mobile
        run: yarn build:web
