name: "Web CI"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.7.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.7.0'

      - name: Install dependencies
        run: |
          yarn install
          npx lerna bootstrap

      - name: Install dependencies
        working-directory: ./packages/web
        run: yarn install

      - name: Lint
        working-directory: ./packages/web
        run: yarn lint

      - name: Build
        working-directory: ./packages/web
        run: yarn build
